version: "3.8"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - type: bind
        source: ./schemas/
        target: /docker-entrypoint-initdb.d/
    ports:
      - 3307:3306
    networks:
      - pedtet
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "host.docker.internal" ]
      timeout: 30s
      interval: 2s
      retries: 15

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
    env_file:
      - .env
    restart: always
    ports:
      - 5000:5000
    networks:
      - pedtet
    environment:
      PORT: 5000
      APP_ENV: devlocal
      BUILD_VERSION: local-build

networks:
  pedtet: {}
